version: 0.0
os: linux
file_exists_behavior: OVERWRITE

files:
  - source: / # Copies everything from the root of my Github repo
    destination: /var/www/React-Crud_nodewithSql_app-mumbai # The deployment path on EC2 instance
hooks:
  ApplicationStop:
    - location: scripts/application_stop.sh
      timeout: 60
      runas: root
  BeforeInstall:
    - location: scripts/cleanup.sh
      timeout: 300
      runas: root  
  AfterInstall:
    - location: scripts/after_install.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: scripts/application_start.sh
      timeout: 120
      runas: root
  ValidateService:
    - location: scripts/validate_service.sh
      timeout: 60
      runas: root

